[theme]
primaryColor = "#bd93f9"          # Roxo (Purple)
backgroundColor = "#282a36"      # Fundo Escuro (Background)
secondaryBackgroundColor = "#44475a" # Cinza Escuro (Current Line/Selection)
textColor = "#f8f8f2"            # Texto (Foreground)
font = "sans serif"